import { createClient } from '@supabase/supabase-js';
import { supabase } from '../utils/supabase';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

const tempSupabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
});

const throwIfError = (error) => {
  if (error) {
    console.error('Supabase error:', error);
    throw error;
  }
};

export const adminApi = {
  async getAllEmployees(companyId) {
    if (!companyId) {
      return [];
    }
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('companyId', companyId)
      .order('name', { ascending: true });
    throwIfError(error);
    return data ?? [];
  },

  async getEmployeeById(id) {
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    throwIfError(error);
    return data;
  },

  async createEmployee(employeeData) {
    // 1. We create user in public.users profile directly.
    // In production, we'd sign up the user via supabase auth or call a secure function.
    // For local dev and demo, we insert the profile record into the 'users' table.
    // Let's generate a temporary ID if not present. Supabase table 'users' usually has id as UUID primary key or serial.
    // Let's see if id can be generated by Supabase or if we need to let Supabase handle it.
    // Typically the 'id' in public.users is linked to auth.users.id.
    // To allow the employee to log in, we can sign them up using Supabase signUp.
    // Let's create an auth user via supabase.auth.signUp if we want them to login.
    // We can do supabase.auth.signUp({ email: employeeData.email, password: employeeData.password || 'temp1234' })
    // and then update their profile.
    
    const email = employeeData.email;
    const tempPassword = employeeData.password || 'employee123';
    
    // Sign up the new user
    const { data: authData, error: authError } = await tempSupabase.auth.signUp({
      email,
      password: tempPassword,
      options: {
        data: {
          full_name: employeeData.name,
          role: employeeData.role || 'Employee',
          companyId: employeeData.companyId
        }
      }
    });

    if (authError) {
      // If user already exists in auth or table, handle it
      if (authError.message.includes('already registered')) {
        // User already in auth. We can try to insert/update profile.
        // Let's throw or handle it.
        throw authError;
      }
      throw authError;
    }

    const authUser = authData?.user;
    if (!authUser) {
      throw new Error('Could not create auth user.');
    }

    // Now insert or update the profile record in public.users table.
    // Since some schemas might use trigger to auto-create, we can check if it exists, or update/insert it.
    // We wait a brief moment for any database triggers to run.
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const payload = {
      id: authUser.id,
      name: employeeData.name,
      full_name: employeeData.name,
      email: employeeData.email,
      role: employeeData.role || 'Employee',
      designation: employeeData.designation,
      phone: employeeData.phone,
      website: employeeData.website,
      location: employeeData.location,
      bio: employeeData.bio,
      department: employeeData.department,
      joining_date: employeeData.joining_date,
      current_address: employeeData.current_address,
      permanent_address: employeeData.permanent_address,
      office_address: employeeData.office_address,
      social_links: employeeData.social_links || {},
      team: employeeData.team || 0,
      awards: employeeData.awards || 0,
      projects: employeeData.projects || 0,
      clients: employeeData.clients || 0,
      avatar: employeeData.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(employeeData.name)}&background=8A3EEA&color=fff`,
      status: employeeData.status || 'active',
      companyId: employeeData.companyId || 1
    };

    // Let's upsert to make sure we don't duplicate or fail if trigger already created it.
    const { data, error: profileError } = await supabase
      .from('users')
      .upsert(payload)
      .select()
      .maybeSingle();

    if (profileError) {
      console.error('Error inserting user profile, but auth user was created:', profileError);
      throw profileError;
    }

    return data;
  },

  async updateEmployee(id, employeeData) {
    const payload = {
      name: employeeData.name,
      full_name: employeeData.name,
      role: employeeData.role,
      designation: employeeData.designation,
      phone: employeeData.phone,
      website: employeeData.website,
      location: employeeData.location,
      bio: employeeData.bio,
      department: employeeData.department,
      joining_date: employeeData.joining_date,
      current_address: employeeData.current_address,
      permanent_address: employeeData.permanent_address,
      office_address: employeeData.office_address,
      social_links: employeeData.social_links || {},
      team: Number(employeeData.team) || 0,
      awards: Number(employeeData.awards) || 0,
      projects: Number(employeeData.projects) || 0,
      clients: Number(employeeData.clients) || 0,
      avatar: employeeData.avatar,
      status: employeeData.status || 'active'
    };

    const { data, error } = await supabase
      .from('users')
      .update(payload)
      .eq('id', id)
      .select()
      .maybeSingle();
    throwIfError(error);
    return data;
  },

  async deleteEmployee(id) {
    // We can do soft delete by setting status = 'inactive'
    const { data, error } = await supabase
      .from('users')
      .update({ status: 'inactive' })
      .eq('id', id)
      .select()
      .maybeSingle();
    throwIfError(error);
    return data;
  },

  async getAllUserDocuments(companyId) {
    if (!companyId) return [];

    // 1. Get all employees belonging to this company
    const employees = await adminApi.getAllEmployees(companyId);
    const companyUserIds = new Set(employees.map(e => e.id));

    if (companyUserIds.size === 0) {
      return [];
    }

    const userIdArray = Array.from(companyUserIds);
    let docs = [];

    // 2. Query Supabase for documents belonging ONLY to users of this company
    try {
      const { data, error } = await supabase
        .from('user_documents')
        .select('*')
        .in('userId', userIdArray);

      if (!error && data) {
        docs = data;
      }
    } catch (e) {
      console.warn('Error fetching user documents from Supabase:', e);
    }

    // 3. Scan localStorage ONLY for user IDs belonging to this company
    try {
      userIdArray.forEach(userId => {
        const localKey = `hrms_user_docs_${userId}`;
        const localStored = localStorage.getItem(localKey);
        if (localStored) {
          const userDocs = JSON.parse(localStored);
          userDocs.forEach(d => {
            if (!docs.some(existing => existing.id === d.id)) {
              docs.push(d);
            }
          });
        }
      });
    } catch (e) {
      console.error('Error scanning local user docs:', e);
    }

    return docs;
  },

  async updateDocumentStatus(documentId, status, rejectionReason = '', userId = null) {
    const payload = {
      status,
      rejectionReason: status === 'Rejected' ? rejectionReason : '',
      lastModified: new Date().toLocaleDateString()
    };

    try {
      const { data, error } = await supabase
        .from('user_documents')
        .update(payload)
        .eq('id', documentId)
        .select()
        .maybeSingle();

      if (!error && data) {
        return data;
      }
    } catch (e) {
      console.warn('Error updating document status in Supabase:', e);
    }

    // Update in localStorage if saved locally
    if (userId) {
      const localKey = `hrms_user_docs_${userId}`;
      const userDocs = JSON.parse(localStorage.getItem(localKey) || '[]');
      const idx = userDocs.findIndex(d => d.id === documentId);
      if (idx !== -1) {
        userDocs[idx] = { ...userDocs[idx], ...payload };
        localStorage.setItem(localKey, JSON.stringify(userDocs));
        return userDocs[idx];
      }
    }

    return { id: documentId, ...payload };
  },

  async approveDocumentRequest(documentId, actionType, userId) {
    if (actionType === 'delete') {
      try {
        await supabase.from('user_documents').delete().eq('id', documentId);
      } catch (e) {}

      if (userId) {
        const localKey = `hrms_user_docs_${userId}`;
        const userDocs = JSON.parse(localStorage.getItem(localKey) || '[]');
        const filtered = userDocs.filter(d => d.id !== documentId);
        localStorage.setItem(localKey, JSON.stringify(filtered));
      }
      return { id: documentId, deleted: true };
    } else {
      // Allow update
      return await adminApi.updateDocumentStatus(documentId, 'Pending', '', userId);
    }
  },

  async rejectDocumentRequest(documentId, userId) {
    const payload = {
      requestStatus: null,
      requestReason: '',
      lastModified: new Date().toLocaleDateString()
    };

    try {
      const { data, error } = await supabase
        .from('user_documents')
        .update(payload)
        .eq('id', documentId)
        .select()
        .maybeSingle();

      if (!error && data) {
        return data;
      }
    } catch (e) {}

    if (userId) {
      const localKey = `hrms_user_docs_${userId}`;
      const userDocs = JSON.parse(localStorage.getItem(localKey) || '[]');
      const idx = userDocs.findIndex(d => d.id === documentId);
      if (idx !== -1) {
        userDocs[idx] = { ...userDocs[idx], ...payload };
        localStorage.setItem(localKey, JSON.stringify(userDocs));
        return userDocs[idx];
      }
    }
    return { id: documentId, ...payload };
  },

  async uploadEmployeeDocument(userId, documentData, companyId = 1) {
    const payload = {
      id: `doc_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
      userId,
      companyId,
      type: documentData.type,
      name: documentData.name,
      url: documentData.url,
      status: 'Approved', // Admin uploaded files are auto-approved
      rejectionReason: '',
      uploadedBy: 'Admin',
      lastModified: new Date().toLocaleDateString(),
      created_at: new Date().toISOString()
    };

    try {
      const { data, error } = await supabase
        .from('user_documents')
        .insert(payload)
        .select()
        .maybeSingle();

      if (!error && data) {
        return data;
      }
    } catch (e) {
      console.warn('Error uploading employee document in Supabase:', e);
    }

    const localKey = `hrms_user_docs_${userId}`;
    const existing = JSON.parse(localStorage.getItem(localKey) || '[]');
    existing.unshift(payload);
    localStorage.setItem(localKey, JSON.stringify(existing));
    return payload;
  }
};
