import { createClient } from '@supabase/supabase-js';
import { supabase } from '../utils/supabase';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

const tempSupabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
});

const throwIfError = (error) => {
  if (error) {
    console.error('Supabase error:', error);
    throw error;
  }
};

export const adminApi = {
  async getAllEmployees(companyId) {
    let query = supabase.from('users').select('*');
    if (companyId) {
      query = query.eq('companyId', companyId);
    }
    const { data, error } = await query.order('name', { ascending: true });
    throwIfError(error);
    return data ?? [];
  },

  async getEmployeeById(id) {
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    throwIfError(error);
    return data;
  },

  async createEmployee(employeeData) {
    // 1. We create user in public.users profile directly.
    // In production, we'd sign up the user via supabase auth or call a secure function.
    // For local dev and demo, we insert the profile record into the 'users' table.
    // Let's generate a temporary ID if not present. Supabase table 'users' usually has id as UUID primary key or serial.
    // Let's see if id can be generated by Supabase or if we need to let Supabase handle it.
    // Typically the 'id' in public.users is linked to auth.users.id.
    // To allow the employee to log in, we can sign them up using Supabase signUp.
    // Let's create an auth user via supabase.auth.signUp if we want them to login.
    // We can do supabase.auth.signUp({ email: employeeData.email, password: employeeData.password || 'temp1234' })
    // and then update their profile.
    
    const email = employeeData.email;
    const tempPassword = employeeData.password || 'employee123';
    
    // Sign up the new user
    const { data: authData, error: authError } = await tempSupabase.auth.signUp({
      email,
      password: tempPassword,
      options: {
        data: {
          full_name: employeeData.name,
          role: employeeData.role || 'Employee',
          companyId: employeeData.companyId
        }
      }
    });

    if (authError) {
      // If user already exists in auth or table, handle it
      if (authError.message.includes('already registered')) {
        // User already in auth. We can try to insert/update profile.
        // Let's throw or handle it.
        throw authError;
      }
      throw authError;
    }

    const authUser = authData?.user;
    if (!authUser) {
      throw new Error('Could not create auth user.');
    }

    // Now insert or update the profile record in public.users table.
    // Since some schemas might use trigger to auto-create, we can check if it exists, or update/insert it.
    // We wait a brief moment for any database triggers to run.
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const payload = {
      id: authUser.id,
      name: employeeData.name,
      full_name: employeeData.name,
      email: employeeData.email,
      role: employeeData.role || 'Employee',
      designation: employeeData.designation,
      phone: employeeData.phone,
      website: employeeData.website,
      location: employeeData.location,
      bio: employeeData.bio,
      department: employeeData.department,
      joining_date: employeeData.joining_date,
      current_address: employeeData.current_address,
      permanent_address: employeeData.permanent_address,
      office_address: employeeData.office_address,
      social_links: employeeData.social_links || {},
      team: employeeData.team || 0,
      awards: employeeData.awards || 0,
      projects: employeeData.projects || 0,
      clients: employeeData.clients || 0,
      avatar: employeeData.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(employeeData.name)}&background=8A3EEA&color=fff`,
      status: employeeData.status || 'active',
      companyId: employeeData.companyId || 1
    };

    // Let's upsert to make sure we don't duplicate or fail if trigger already created it.
    const { data, error: profileError } = await supabase
      .from('users')
      .upsert(payload)
      .select()
      .maybeSingle();

    if (profileError) {
      console.error('Error inserting user profile, but auth user was created:', profileError);
      throw profileError;
    }

    return data;
  },

  async updateEmployee(id, employeeData) {
    const payload = {
      name: employeeData.name,
      full_name: employeeData.name,
      role: employeeData.role,
      designation: employeeData.designation,
      phone: employeeData.phone,
      website: employeeData.website,
      location: employeeData.location,
      bio: employeeData.bio,
      department: employeeData.department,
      joining_date: employeeData.joining_date,
      current_address: employeeData.current_address,
      permanent_address: employeeData.permanent_address,
      office_address: employeeData.office_address,
      social_links: employeeData.social_links || {},
      team: Number(employeeData.team) || 0,
      awards: Number(employeeData.awards) || 0,
      projects: Number(employeeData.projects) || 0,
      clients: Number(employeeData.clients) || 0,
      avatar: employeeData.avatar,
      status: employeeData.status || 'active'
    };

    const { data, error } = await supabase
      .from('users')
      .update(payload)
      .eq('id', id)
      .select()
      .maybeSingle();
    throwIfError(error);
    return data;
  },

  async deleteEmployee(id) {
    // We can do soft delete by setting status = 'inactive'
    const { data, error } = await supabase
      .from('users')
      .update({ status: 'inactive' })
      .eq('id', id)
      .select()
      .maybeSingle();
    throwIfError(error);
    return data;
  }
};
